server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      # ≤÷ø‚∑÷÷ß
      label: master
      server:
        git:
          # git≤÷ø‚µÿ÷∑
          uri: https://github.com/nhx7103972/springCloudStudy
          # ≤÷ø‚¬∑æ∂
          searchPaths: springCloud.config/respo
          username: 
          password: 



