server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/nhx7103972/springCloudStudy
          searchPaths: respo
          username: 
          password: 



